### ISSUE TITLE
Automatic Server IP/Port Configuration

### ISSUE THREAD

**Issue by jzhang27143** [jzhang27143/federated_rc#1]
Currently, the server binds to and IP Address and Port provided in a config file. The reason is that for clients to connect wirelessly, the server must specifically bind to the address of the wifi interface (wlan0 on Windows or wifi0 on Linux). This address can be found via the ipconfig/ifconfig command.

Task: Simplify server network configuration by adding code in src/server.py to automatically discover the wifi interface address and automatically assign ports to incoming connections. Then remove unnecessary code in src/server.py: configure().

**Comment by Suhas7** [comment]
This mostly works, it doesn't autodetect but you can pick your interface.
