### ISSUE TITLE
Allow non-iid distribution of MNIST data

### ISSUE THREAD

**Issue by jzhang27143** [jzhang27143/federated_rc#11]
Currently, test/test_mnist_fed_avg_client.py selects a training subset of MNIST with uniform probability. Typical use cases of a federated scheme will have non-iid sample distributions i.e. skewed towards certain digits in MNIST.

Task: write a client configuration in which users can specify skewed label distributions. One approach for integration may be to add a '--mnist [skewed digits]' flag in the client argparse.

**Comment by matthew-j** [comment]
I'll take this
